import { Translation } from 'primeng/api';

export const TRADUCCION_ESP: Translation = {
  before: 'Antes',
  dateBefore: 'La fecha debe ser anterior a la actual',
  dateAfter: 'La fecha debe ser posterior a la actual',
  accept: 'Aceptar',
  reject: 'Rechazar',
  choose: 'Elegir',
  upload: 'Subir',
  cancel: 'Cancelar',
  after: 'Después',
  dateIs: 'La fecha es',
  dayNames: [
    'Domingo',
    'Lunes',
    'Martes',
    'Miercoles',
    'Jueves',
    'Viernes',
    'Sabado',
  ],
  dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
  dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
  monthNames: [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre',
  ],
  monthNamesShort: [
    'Ene',
    'Feb',
    'Mar',
    'Abr',
    'May',
    'Jun',
    'Jul',
    'Ago',
    'Sep',
    'Oct',
    'Nov',
    'Dic',
  ],
  today: 'Hoy',
  clear: 'Limpiar',
  // eslint-disable-next-line quotes
  dateFormat: "dd 'de' M 'del' yy",
  weekHeader: 'Semana',
  emptyMessage: 'No hay datos para mostrar',
  emptyFilterMessage: 'No hay datos para mostrar',
  addRule: 'Agregar regla',
  removeRule: 'Eliminar regla',
  apply: 'Aplicar',
  contains: 'Contiene',
  dateIsNot: 'La fecha no es',
  endsWith: 'Termina con',
  equals: 'Es igual a',
  gt: 'Mayor que',
  gte: 'Mayor o igual que',
  is: 'Es',
  isNot: 'No es',
  lt: 'Menor que',
  lte: 'Menor o igual que',
  matchAll: 'Coincidir todo',
  matchAny: 'Coincidir alguno',
  medium: 'Medio',
  noFilter: 'Sin filtro',
  notContains: 'No contiene',
  notEquals: 'No es igual a',
  passwordPrompt: 'Ingrese la contraseña',
  startsWith: 'Empieza con',
  strong: 'Fuerte',
  weak: 'Débil',
};
